#!/bin/sh

bspc config border_width       5
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc config presel_border_color "#FFFFFF"
bspc config focused_border_color "#3366AA"
bspc config auto_cancel on

bspc monitor DVI-I-2 -d        # Terminals WWW Graphics Dev Social Torrent Games
bspc monitor DVI-I-3 -d TV

bspc rule -a Blender desktop=^3 follow=on
bspc rule -a irssi desktop=^5
bspc rule -a qbittorrent desktop=^6 follow=on
bspc rule -a Steam desktop=^7 follow=off
bspc rule -a Gimp desktop=^3 follow=on floating=on

setxkbmap -layout se
xrandr --output DVI-I-3 --auto --right-of DVI-I-2
bspc config bottom_padding 20
hsetroot -solid #333333
feh --bg-tile ~/Pictures/ShatteredIslandsTiles.gif
#compton --backend glx --paint-on-overlay --vsync opengl-swc &
mousesettings
dunst &
bmpanel2 &
checkmail &
resumeirc &
steam &
resize_bspwm.sh &
